### ISSUE TITLE
run

### ISSUE THREAD

**Issue by chnasln** [TheMasterRoot/People-Counter-By-Area#1]
hi , How are you ?
Can you help me?
![Adsız](https://user-images.githubusercontent.com/67520627/86009971-7a7f3480-ba23-11ea-9d60-8ae659da4814.png)

**Comment by TheMasterRoot** [comment]
sure. whats wrong?

**Comment by chnasln** [comment]
I sent the picture exactly what the IP address does when I run the program looks like the picture

**Comment by TheMasterRoot** [comment]
your local host IP. http://127.0.0.1:5000
or if your in another pc you nee dto get ip from machine that are running the code

**Comment by chnasln** [comment]
can you connect to my computer

**Comment by TheMasterRoot** [comment]
give me your teamviewer or anydesk ID

**Comment by chnasln** [comment]
teamviwer ıd:1 720 540 631
passworld :feq392
